import React from "react"
import "./Meme.css"
import { useDispatch } from "react-redux";

/** Meme component used to display individual meme.
 * Data populated from store.
 * Uses dispatch to remove itself from the store on click.
 *  Props:
 *    id: Unique string, generated by UUID.
 *    top: String to display at top of meme.
 *    bottom: string to display at bottom of meme.
 *    image: string URL address for background image of meme.
 */

function Meme({ id, top, bottom, image }){
  const dispatch = useDispatch();
  const style = {
    backgroundImage: `url(${image})`
  }

  // Removes self from store.
  function remove() {
    dispatch({type: "REMOVE", payload: id});
  }

  return (
    <div className="Meme" style={style} onClick={remove}>
    <h3>{top}</h3>
    <h3>{bottom}</h3>
    </div>
  )
}

export default Meme;